### ISSUE TITLE
Error on port 80 landing page: Attempted to load class "Memcached" from the global namespace

### ISSUE THREAD

**Issue by faceleg** [superdesk/web-publisher#1032]
<img width="1792" alt="Screen Shot 2020-01-10 at 4 03 08 PM" src="https://user-images.githubusercontent.com/1000759/72122489-ec56b980-33c2-11ea-8a69-b72f7bd9f1d4.png">
 
After following the instructions here: https://superdesk-publisher.readthedocs.io/en/latest/manual/getting_started/installing-publisher.html and attempting to access localhost:80, I get the error in the above screenshot.

``` 
(1/1) ClassNotFoundExceptionAttempted to load class "Memcached" from the global namespace.Did you forget a "use" statement?
--
```

What might I do to resolve this?

**Comment by ahilles107** [comment]
You need to have memcachED installed as a library AND as a php extension in your system
