### ISSUE TITLE
Theme could not be installed, files are reverted to previous version!

### ISSUE THREAD

**Issue by th3root** [superdesk/web-publisher#1047]
Hi, I got problem when i did installed themes with this command: 
**php bin/console swp:theme:install pyne3x src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/ -f -p -a**

**Theme could not be installed, files are reverted to previous version!**
Error message: Failed to remove file "/var/www/publisher/var/cache/prod/twig/pyne3x/themes/swp_default-theme/c362e4f52f6a824ac4d5ad6d2effb0cf5db0c82847d47c632065554137692a4c.php": unlink(/var/www/publisher/var/cache/prod/twig/pyne3x/themes/swp_default-theme/c362e4f52f6a824ac4d5ad6d2effb0cf5db0c82847d47c632065554137692a4c.php): Permission denied

Thanks in advance

**Comment by ahilles107** [comment]
Hey, error is at end of you log ;)

`Permission denied` - make sure that your user have right to write in `/var/www/publisher/var/cache/` directory.
