### ISSUE TITLE
Tenant for host could not be found

### ISSUE THREAD

**Issue by NicholasIanni** [superdesk/web-publisher#1106]
**Info**:
192.168.70.133 - SuperDesk installed
192.168.70.140 SuperDesk Publisher installed

**Issue**:
SuperDesk is installed and seems to work ok when accessed (http://192.168.70.133/#/workspace), however, after following the instructions at https://superdesk-publisher.readthedocs.io/en/latest/manual/getting_started/installing-publisher.html , and attempting to access the Publisher page at (192.168.70.140), I just get a page that says "Tenant for host "192.168.70.140" could not be found!

I am not sure what, if any, information is needed to assist me with this issue, but I will provide anything that is needed.

**Comment by ahilles107** [comment]
Hey, we are aware about problem in tenant resolver and figuring out host from IP adres. Can you assign hostnames to those ip's? Like superdesk.dev and publisher.dev or something similar.

**Comment by NicholasIanni** [comment]
Can I do this through the hosts file or does it have to be done on network side?

**Comment by NicholasIanni** [comment]
I just added the hostnames in the hosts file on the client machine for dev. Works now. Thank you!
