### ISSUE TITLE
User is not redirected back to previous route after following successful OAuth flow

### ISSUE THREAD

**Issue by kottkrig** [superdesk/web-publisher#1115]
## Expected Behavior
As a user, I expect to be redirected to the article I was reading after a successful login via `/connect/oauth`.

## Current Behavior
I'm redirected to the homepage `/` after logging in via `/connect/oauth`.

## Possible Solution
Can we save the current user route when user initiates the OAuth flow in `/connect/oauth`? And then redirect back to it after a successful login at `/connect/oauth/check`. Right now, the OAuthController always redirects to the "homepage" route after a successful login:

https://github.com/superdesk/web-publisher/blob/6a36074e524f94046585a328237069e2d6698e39/src/SWP/Bundle/CoreBundle/Controller/ExternalOauthController.php#L31-L50

## Steps to Reproduce

1. Navigate to route other than homepage
2. Click on a link that navigates to `/connect/oauth`
3. Follow the oauth flow

**Comment by ahilles107** [comment]
I would not start session at this point yet, so maybe this redirect can be configurable by env, or can be part of `check` route query params?

**Comment by kottkrig** [comment]
Making it configurable by env wouldn't solve this particular issue since we want users to be redirected back to a dynamic route depending on which route the user is visiting when they initiate the login flow: Something like `https://publisher.domain/route-slug/article-slug`.

But adding it to a query param might be a solution. Is it also possible to send that as a query param through the oauth flow? Something like:

1. Add query variable to the login-start route  `/connect/oauth?redirect_to=https://publisher.domain/route-slug/article-slug`
2. Add query variable to the external oauth request in `/connect/oauth` https://github.com/superdesk/web-publisher/blob/6a36074e524f94046585a328237069e2d6698e39/src/SWP/Bundle/CoreBundle/Controller/ExternalOauthController.php#L26-L28
3. Receive query in `/connect/oauth/check/` and conditionally redirect to the value of the query param or fallback to 'homepage' https://github.com/superdesk/web-publisher/blob/6a36074e524f94046585a328237069e2d6698e39/src/SWP/Bundle/CoreBundle/Controller/ExternalOauthController.php#L31-L50

**Comment by ahilles107** [comment]
This is something what You would need to check. I don't have experience with it. But sound's like good solution for me.

**Comment by kottkrig** [comment]
OAuth doesn't seem to support just adding an additional query param. One possible solution would be to base64 encode this value and store it in the oauth `state` value.

But I cannot figure out if it's possible to send our own state to `knpuniversity/oauth2-client-bundle`. Based on the code below it seems to pull that state from the provider with no possibility to change it:

https://github.com/knpuniversity/oauth2-client-bundle/blob/b4791efd921e9a6af60542c440cf66b5456b97d9/src/Client/OAuth2Client.php#L70-L75

That state is also added to a new session `self::OAUTH2_SESSION_STATE_KEY`. If all else fail, can we add a new key `OAUTH2_SESSION_ORIGIN` that is cleaned up after successful login?

**Comment by takeit** [comment]
hey @kottkrig 

storing the route in `state` would be the best solution here.

From what I see you can set custom `state` by passing it to the 2nd (`options`) argument here https://github.com/knpuniversity/oauth2-client-bundle/blob/v1/src/Client/OAuth2Client.php#L61

This function https://github.com/knpuniversity/oauth2-client-bundle/blob/v1/src/Client/OAuth2Client.php#L67 will then set the custom state and here https://github.com/knpuniversity/oauth2-client-bundle/blob/v1/src/Client/OAuth2Client.php#L73 it will load your custom state and save it in the session. Then in the `/connect/oauth/check` you would be able to retrieve that state and redirect users to the route they clicked `Login`.

**Comment by kottkrig** [comment]
> This function https://github.com/knpuniversity/oauth2-client-bundle/blob/v1/src/Client/OAuth2Client.php#L67 will then set the custom state and here https://github.com/knpuniversity/oauth2-client-bundle/blob/v1/src/Client/OAuth2Client.php#L73

You're absolutely right. I missed that in my read-through of the code. 👍 

Hopefully I will find time to test this out during the week. Otherwise I will try it next week.
