### ISSUE TITLE
[Insight] Database queries should use parameter binding - in src/SWP/…/Loader/ArticleLoader.php, line 142

### ISSUE THREAD

**Issue by ahilles107** [superdesk/web-publisher#112]
**[in src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, line 142](https://github.com/superdesk/web-publisher/blob/d5a8e2093afc50f38788674e97fa6b8df2030d53/src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php#L142)**

> If provided by the user, the value of `$order[0]` may allow an SQL injection attack. Avoid concatenating parameters to SQL query strings, and use parameter binding instead.

```php
                            throw new \Exception('Order filter must have two parameters with second one asc or desc, e.g. order(id, desc)');
                        }
                        if ($order[0] === 'id') {
                            $order[0] = 'jcr:uuid';
                        }
                        $queryStr .= ' ORDER BY S.'.$order[0].' '.$order[1];
                    }

                    $query = $this->dm->createPhpcrQuery($queryStr, QueryInterface::JCR_SQL2);

                    if (isset($parameters['limit'])) {
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/c1d40e6d-f4c3-42fa-af0e-d4a4e521d435/analyses/8?status=violations)_

**Comment by djbrd-sourcefabric** [comment]
Unfortunately, for the \Jackalope\Query\Query class has the following implementation of the bindValue method:
    public function bindValue($varName, $value)
    {
        throw new RepositoryException('Not Implemented...');
    }

**Comment by djbrd-sourcefabric** [comment]
But I will use mysql_real_escape_string to prevent sql injection

**Comment by ahilles107** [comment]
Have hope that you mean `mysqli_real_escape_string`. And how about http://php.net/manual/en/pdo.quote.php?
