### ISSUE TITLE
Can't install default theme

### ISSUE THREAD

**Issue by gordan-cuic** [superdesk/web-publisher#1126]
I pulled code from 2.1 brach. Instructions taken from https://superdesk-publisher.readthedocs.io/en/latest/manual/getting_started/installing-publisher.html

Basically, when working in dev environment,
`php bin/console swp:theme:install <my tenant code> src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/ -f -p -a` returns `Undefined column: 7 ERROR:  column "profile" of relation "swp_item" does not exist`

I tried added it manually (`alter table swp_item add column profile varchar;`), just to see what's gonna happen, but then `swp:theme:install` returned  `index: /swp_index/package/4 caused Rejecting mapping update to [swp_index] as the final mapping would have more than 1 type: [article, package]` (this is the same error mentioned in #766 )

Does anybody know what might be the cause of this?

**Comment by mabastaraz** [comment]
same problem here 
https://github.com/superdesk/web-publisher/issues/1125
