### ISSUE TITLE
Tenant for host could not be found

### ISSUE THREAD

**Issue by trondhuso** [superdesk/web-publisher#1158]
Hi,

I have installed publisher, but when I run the website I am getting Tenant for host 'example.com' (to hide the original domain) could not be found! Please check tenants configuration.

1) What is a tenant
2) Where is the tenant config?

**Comment by trondhuso** [comment]
@petrjasek Any suggestions?

**Comment by greg606** [comment]
Hello @trondhuso best to load sample data which includes sample tenant 
e.g. this way: https://github.com/superdesk/web-publisher/tree/2.1/etc/docker#load-fixtures

**Comment by greg606** [comment]
Documentation can also be useful: 
https://superdesk-publisher.readthedocs.io/en/latest/manual/getting_started/installing-publisher.html?highlight=tenant#create-an-organization-and-tenant

**Comment by trondhuso** [comment]
@greg606 Thanks for the first comment. I will check that one out so I can understand the tenant part.
I did follow the steps in your second link. For some reason it still returns the message.

Thanks for the pointers. I will investigate further.

**Comment by greg606** [comment]
Also please make sure you added tenant with exact the same domain as in publisher url.

**Comment by greg606** [comment]
@trondhuso How is the progress with it? Can we close it?

**Comment by trondhuso** [comment]
Not going so well I would say:

Creating organization
```
SYMFONY_ENV=prod php bin/console swp:organization:create oiwow
Organization oiwow (code: bbecjh) has been created and enabled!
```

Creating tenant:
```
php bin/console swp:tenant:create bbecjh oiwow.no publisher
Please enter subdomain:publisher
Tenant publisher (code: 2v76qc) has been created and enabled!
```
website: publisher.oiwow.io

**Comment by greg606** [comment]
and what you have in database in swp_tenant -> domain_name

**Comment by greg606** [comment]
and also subdomain there

**Comment by trondhuso** [comment]
subdomain = publisher
domain_name = oiwow.no - I corrected it and it seems to be working better now.

closing due to this correction sent me one step further.
