### ISSUE TITLE
grunt build - GC - Javascript heap out of memory

### ISSUE THREAD

**Issue by trondhuso** [superdesk/web-publisher#1159]
Hi,

Has anyone experienced Javascript heap out of memory when installing the publisher plugin in superdesk?

I am running grunt-build after adding to package.json
´"superdesk-publisher": "superdesk/superdesk-publisher#master"´

```
 Running "ngtemplates:core" (ngtemplates) task
File /opt/superdesk/client/node_modules/superdesk-core/templates-cache.generated.js created.

Running "webpack:build" (webpack) task
 92% chunk asset optimization                                                             
<--- Last few GCs --->

[2548:0x2868660]   271136 ms: Mark-sweep 1403.1 (1498.0) -> 1402.9 (1498.5) MB, 2140.5 / 0.0 ms  allocation failure GC in old space requested
[2548:0x2868660]   273230 ms: Mark-sweep 1402.9 (1498.5) -> 1402.9 (1483.5) MB, 2094.3 / 0.0 ms  last resort 
[2548:0x2868660]   275212 ms: Mark-sweep 1402.9 (1483.5) -> 1402.9 (1483.5) MB, 1981.6 / 0.0 ms  last resort
```

Upgraded the server to 8gb ram without much luck, so going down to 4gb again. (test server)

any suggestions welcome

Trond

**Comment by kottkrig** [comment]
You can increase the max memory usage for Node with the `NODE_OPTIONS` env variable.

```
NODE_OPTIONS="--max-old-space-size=4096"
```

**Comment by trondhuso** [comment]
Thanks. So I did and it worked nicely. 

My command is now:
`node --max-old-space-size=2048 /usr/bin/grunt build`
