### ISSUE TITLE
Bug: Article updatedAt field is updated when media is converted to webp

### ISSUE THREAD

**Issue by kottkrig** [superdesk/web-publisher#1215]
## Current behaviour

Currently, in `swp_article` table, the value in column `updated_at` is updated each time the article's media renditions are converted to webp. 

Here are some rows from our database where we can see that `updated_at` is set to the same timestamp as `media_updated_at`. These articles haven't been modified in any way other than the article images being converted to webp.

| id    | created_at          | updated_at          | media_updated_at    |
|-------|---------------------|---------------------|---------------------|
| 44152 | 2021-11-23 10:31:13 | 2021-11-24 16:05:22 | 2021-11-24 16:05:22 |
| 44151 | 2021-11-23 10:04:25 | 2021-11-24 16:02:49 | 2021-11-24 16:02:49 |
| 44150 | 2021-11-23 09:58:29 | 2021-11-24 16:02:40 | 2021-11-24 16:02:40 |
| 44149 | 2021-11-23 09:53:33 | 2021-11-24 16:02:16 | 2021-11-24 16:02:16 |
| 44148 | 2021-11-23 09:41:27 | 2021-11-24 16:02:07 | 2021-11-24 16:02:07 |
| 44147 | 2021-11-23 09:31:17 | 2021-11-24 16:01:53 | 2021-11-24 16:01:53 |

## Expected behaviour

Only the column `media_updated_at` should be updated on each webp conversion. `updated_at` should not be altered.

## Possible fix/solution?

We haven't been able to pinpoint the code that is responsible for the updated `updated_at` field. Is this perhaps an expected Symfony behaviour?

As far as we can see, the ImageConversionHandler seems to be doing the correct thing. It updates the `media_updated_at` field.

https://github.com/superdesk/web-publisher/blob/ef8afc6cdefab1b0fde38063c38eefd1c508590d/src/SWP/Bundle/CoreBundle/MessageHandler/ImageConversionHandler.php#L132-L139

**Comment by takeit** [comment]
There is a [gedmo timestampable extension enabled](https://github.com/superdesk/web-publisher/blob/master/src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Article.orm.yml#L40) (it comes from [this library](https://github.com/stof/StofDoctrineExtensionsBundle)) that is updating the `updatedAt` timestamp whenever the Article object gets updated. In that case, when the `media_updated_at` gets updated.

You can disable the timestampable extension in the Article entity when the `media_updated_at` gets updated. It can be done by implementing [TimestampableCancelInterface](https://github.com/superdesk/web-publisher/blob/master/src/SWP/Bundle/ContentBundle/Doctrine/TimestampableCancelInterface.php) on Article entity and then doing [this](https://github.com/superdesk/web-publisher/blob/master/src/SWP/Bundle/CoreBundle/EventSubscriber/HandleArticleChangeSubscriber.php#L75-L77).

Here is the [PR](https://github.com/superdesk/web-publisher/pull/683/files#diff-9eec7999aa8b5fc96b41911693bb17885ef2602bd60e1af1ce5d04a75880feddR66) where it was implemented for other use case.

**Comment by kottkrig** [comment]
@takeit thank you!

The following code works perfectly well for our use case. Converted renditions no longer update the article `updatedAt` field. Would this fix be valuable as a Pull Request?

```php
private function markArticlesMediaAsUpdated($image)
{
    /** @var ImageRenditionInterface[] $articleMedia */
    $articleMedia = $this->imageRenditionRepository->findBy(['image' => $image]);
    foreach ($articleMedia as $media) {
        $media->getMedia()->getArticle()->setMediaUpdatedAt(new DateTime());
        $media->getMedia()->getArticle()->cancelTimestampable(true);
    }
}
```

**Comment by takeit** [comment]
@kottkrig definitely! Go ahead.
