### ISSUE TITLE
No tenant for host

### ISSUE THREAD

**Issue by nalyk** [superdesk/web-publisher#361]
I followed the "local" install instructions, i created default tenant as well as another tenant. I installed the theme for respective tenant/organisation, but i get a:
 
`==> /var/log/nginx/unimedia.altfel.md.error.log <==
2017/06/27 14:18:48 [error] 8481#0: *11325 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught SWP\Component\MultiTenancy\Exception\TenantNotFoundException: Tenant for host "unimedia.altfel.md" could not be found! in /var/www/unimedia.altfel.md/htdocs/app/cache/prod/classes.php:7705
`

can you please give me more details on what am i doing wrong and how can i fix it? thank you.

**Comment by ahilles107** [comment]
Hey, 

in database table swp_tenant you need to set `altfel.md` as domain and `unimedia` as subdomain values for your tenant.

**Comment by ahilles107** [comment]
When you create new tenant - console command have domain ans subdomain parameters. 
```
php app/console swp:tenant:create --help
Usage:
  swp:tenant:create [options] [--] [<organization code>] [<domain>] [<name>] [<subdomain>]

Arguments:
  organization code     Organization code
  domain                Domain name
  name                  Tenant name
  subdomain             Subdomain name```

If You use option `default` then domain is set to you parameters.yml `domain` parameter value.

**Comment by ahilles107** [comment]
Sorry for long reply - we somehow missed that notification.

**Comment by nalyk** [comment]
Thank you, "fixed" it meanwhile, adding the right values directly into DB.
