### ISSUE TITLE
[Request] Update installation instructions

### ISSUE THREAD

**Issue by mgogoulos** [superdesk/web-publisher#412]
Can you please provide more detailed instructions as to how to get the Publisher working? I have been trying on Ubuntu 16.04, on master branch, getting all sort of errors.

- What is the suggested operating system?  
- The docker install instructions really confuse me. There's a build section, then a run section, then a pre-configuration, then an install, then a post-configuration. Please specify what is the order of these commands so that you can get the Publisher running
- I tried the docker version and composer breaks with the following:
```
root@me:/tmp/markos/web-publisher/docker# docker-compose run php composer install
...
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.1 but your PHP version (7.0.25) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/annotations v1.5.0 -> satisfiable by doctrine/annotations[v1.5.0].
    - doctrine/annotations v1.5.0 requires php ^7.1 -> your PHP version (7.0.25) does not satisfy that requirement.
 ...
```
- what is a way to deploy this, once it gets installed? The doc mentions

```
php app/console server:start publisher.dev
```

but it would be helpful if you added more information, is this for a dev environment only or can be used in production?

Happy to test any instructions and provide feedback

Regards,
Markos

**Comment by CrazyEyesPete** [comment]
Agreeing with Markos,
I'm seeing a few demos of Publisher working but unable to get it working myself. Having the same requirement issues as Markos mentioned in his post.

**Comment by takeit** [comment]
Hi, thanks for your report, you are right - it might be confusing.

We will include it in the future sprint and will try to update the documentation in the upcoming days.

**Comment by CrazyEyesPete** [comment]
Thanks takeit,

I was referenced this script to help install the requirements : https://gist.github.com/ahilles107/96b5cdc0da6300fc4c3f4dc6d13a1074

This did complete without error, but still not seeing all the features that are available in the demo videos.

I'm looking at your link to help with running on a production server now.

**Comment by ahilles107** [comment]
Hey @CrazyEyesPete - this script installs Superdesk with client from sdsite branch - with Publisher management configured. In installed Superdesk You should have `Publisher` section in left menu.

**Comment by CrazyEyesPete** [comment]
Thanks @ahilles107  Do you mean your script I referenced above? Or is there something new that I'm not seeing?

**Comment by ahilles107** [comment]
Yes, i talk about my gist.

**Comment by vijayanj** [comment]
Received the Following error while adding a new website in the publisher.

Error. Try again later.

**Comment by ahilles107** [comment]
@vijayanj you tried to add it by API, or console command? How looked your call, and maybe you have stack trace?

**Comment by vijayanj** [comment]
I tried through the console command (dashboard).

**Comment by takeit** [comment]
Hi, please check [how to install Superdesk Publisher guide](http://superdesk-publisher.readthedocs.io/en/latest/manual/getting_started/superdesk-superdesk-publisher-setup.html) (and/or configure it with Superdesk).
