### ISSUE TITLE
Unable to find template "index.html.twig"

### ISSUE THREAD

**Issue by mkhader88** [superdesk/web-publisher#449]
Hi
How i can change the path of the them directory, i got this error because the system is searching in the wrong path
Unable to find template "index.html.twig" (looked into: /var/www/publisher/app/Resources/views, /var/www/publisher/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form, /var/www/publisher/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views).

but the path for the them in app/themes/Tenant-name

Can you help me with this issue please

Thanks in Advance

**Comment by takeit** [comment]
Hi @mkhader88 

the theme should be stored (in your case) here `/var/www/publisher/app/themes/<tenant_code>`.

It should be the `tenant's code` not the `tenant's name`.

Are you installing the default theme? (`php app/console swp:theme:install <tenant> src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/ -f`) or your custom one?

Please, check also https://www.superdesk.org/news/installing-superdesk-publisher. There is a guide on how to exactly setup Superdesk Publisher using the default theme.

**Comment by mkhader88** [comment]
Hi @takeit  
Thank you for your reply, when i used the steps in this link https://www.superdesk.org/news/installing-superdesk-publisher in the step below i got this error
4. CREATE THE DATABASE AND UPDATE THE SCHEMA
SYMFONY_ENV=prod php app/console doctrine:database:create

error: An exception occurred in driver: SQLSTATE[08006] [7] fe_sendauth: no password supplied 

i added the postgres user and pass to the parameters.yml file in app/config

but when i remove the SYMFONY_ENV=prod from the command everything is working fine

do you have a solution for this issue ?

Thanks in advance

**Comment by takeit** [comment]
Hi @mkhader88, no idea, we will need to check it, it went all fine here on our side without this issue. Looks like it is an issue with the postgres and pg_hba.conf file configuration.

**Comment by mkhader88** [comment]
Thank you for your swift response,

I have 2 more questions if you dont mind.
1- does superdesk support live streaming and broadcasting? 
2- does superdesk support other languages in the superdesk admin panel or atleast can we change the labels for each field to the desired language?

Thanks in advance

**Comment by petrjasek** [comment]
hey,
re 1: not really
re 2: yes you can change language in superdesk on user profile page, we do translations on [transifex](https://www.transifex.com/sourcefabric/superdesk/)
