### ISSUE TITLE
Command error while installing dependencies

### ISSUE THREAD

**Issue by jvkiran** [superdesk/web-publisher#508]
Install Superdesk Publisher source code dependencies:

HTTPDUSER=$(ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\ -f1) && sudo chown -R "$HTTPDUSER":"$HTTPDUSER" publisher/ && cd publisher && sudo -u www-data SYMFONY_ENV=prod composer install --no-dev --optimize-autoloader

**error code:  cut: the delimiter must be a single character**

After try with some ' ' fix, below problems are facing.

 HTTPDUSER=$(ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d ' ' -f1) && sudo chown -R "$HTTPDUSER":"$HTTPDUSER" publisher/ && cd publisher && sudo -u www-data SYMFONY_ENV=prod composer install --no-dev --optimize-autoloader
Cannot create cache directory /home/telugram/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/telugram/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for layershifter/tld-database 1.0.56 -> satisfiable by layershifter/tld-database[1.0.56].
    - layershifter/tld-database 1.0.56 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 2
    - Installation request for marc1706/fast-image-size v1.1.4 -> satisfiable by marc1706/fast-image-size[v1.1.4].
    - marc1706/fast-image-size v1.1.4 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 3
    - Installation request for php-amqplib/php-amqplib v2.7.2 -> satisfiable by php-amqplib/php-amqplib[v2.7.2].
    - php-amqplib/php-amqplib v2.7.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
  Problem 4
    - Installation request for react/zmq dev-master -> satisfiable by react/zmq[dev-master].
    - react/zmq dev-master requires ext-zmq * -> the requested PHP extension zmq is missing from your system.
  Problem 5
    - Installation request for sentry/sentry 1.8.4 -> satisfiable by sentry/sentry[1.8.4].
    - sentry/sentry 1.8.4 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 6
    - Installation request for symfony/symfony v3.4.6 -> satisfiable by symfony/symfony[v3.4.6].
    - symfony/symfony v3.4.6 requires ext-xml * -> the requested PHP extension xml is missing from your system.
  Problem 7
    - symfony/symfony v3.4.6 requires ext-xml * -> the requested PHP extension xml is missing from your system.
    - willdurand/hateoas-bundle 1.4.0 requires symfony/framework-bundle ~2.3 || ~3.0 || ~4.0 -> satisfiable by symfony/symfony[v3.4.6].
    - Installation request for willdurand/hateoas-bundle 1.4.0 -> satisfiable by willdurand/hateoas-bundle[1.4.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by ahilles107** [comment]
Hey, you need to install curl, mbstring, bcmath, zmq and xml extensions for php on your server.

**Comment by jvkiran** [comment]
Thanks
