### ISSUE TITLE
Error while database creation

### ISSUE THREAD

**Issue by jvkiran** [superdesk/web-publisher#515]
telugram@localhost:/var/www/publisher$ sudo /etc/init.d/postgresql reload
[ ok ] Reloading postgresql configuration (via systemctl): postgresql.service.
telugram@localhost:/var/www/publisher$ SYMFONY_ENV=prod php app/console doctrine:database:create
10:29:24 ERROR     [console] Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[08006] [7] fe_sendauth: no password supplied" ["exception" => Doctrine\DBAL\Exception\ConnectionException { …},"command" => "doctrine:database:create","message" => "An exception occurred in driver: SQLSTATE[08006] [7] fe_sendauth: no password supplied"] []

In AbstractPostgreSQLDriver.php line 89:
                                                                                          
  An exception occurred in driver: SQLSTATE[08006] [7] fe_sendauth: no password supplied  
                                                                                          

In PDOConnection.php line 47:
                                                         
  SQLSTATE[08006] [7] fe_sendauth: no password supplied  
                                                         

In PDOConnection.php line 43:
                                                         
  SQLSTATE[08006] [7] fe_sendauth: no password supplied  

Please help.

**Comment by ahilles107** [comment]
it's not a bug related to Publisher - it's wrong postgres configuration.
