### ISSUE TITLE
There are no commands defined in the "rabbitmq-supervisor" namespace

### ISSUE THREAD

**Issue by jvkiran** [superdesk/web-publisher#517]
command: sudo -u www-data SYMFONY_ENV=prod php app/console rabbitmq-supervisor:build --env=prod

**error: There are no commands defined in the "rabbitmq-supervisor" namespace**

Also rabbitmq-server and supervisor both services are running in production server.

i'm following this tutorial for [setup process](https://www.superdesk.org/news/installing-superdesk-publisher) 
Need help

**Comment by jvkiran** [comment]
Hi @takeit ,
Thanks for the update, will configure the supervisor accordingly.

**Comment by netmonk** [comment]
This install guide is still outdated, and generating the same error. Please proceed to update this installation guide.
