### ISSUE TITLE
Publisher - Output Settings - Add Site - 404 error 

### ISSUE THREAD

**Issue by jvkiran** [superdesk/web-publisher#518]
Hello,
Trying to add site and theme, but issue.

Request Url: http://localhost:5000/api/v1/tenants/
params:
tenant: {
domainName: xsaxsaxsa
name: xsxsa
}
Response error: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again

Stuck at this step, please help.

**Comment by takeit** [comment]
Duplicate of https://github.com/superdesk/superdesk-publisher/issues/28
