### ISSUE TITLE
NonUniqueResultException 

### ISSUE THREAD

**Issue by jvkiran** [superdesk/web-publisher#522]
2018/05/26 05:04:17 [error] 13218#13218: *425 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Doctrine\ORM\NonUniqueResultException: More than one result was found for query although one row or none was expected. in /var/www/publisher/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:770
Stack trace:
#0 /var/www/publisher/src/SWP/Bundle/MultiTenancyBundle/Doctrine/ORM/TenantRepository.php(59): Doctrine\ORM\AbstractQuery->getOneOrNullResult()
#1 /var/www/publisher/src/SWP/Component/MultiTenancy/Resolver/TenantResolver.php(54): SWP\Bundle\MultiTenancyBundle\Doctrine\ORM\TenantRepository->findOneByDomain('139.162.61.246')
#2 /var/www/publisher/app/cache/prod/ContainerEfjtltv/TenantResolver_98081b0.php(13): SWP\Component\MultiTenancy\Resolver\TenantResolver->resolve('139.162.61.246')
#3 /var/www/publisher/src/SWP/Bundle/CoreBundle/Context/CachedTenantContext.php(74): TenantResolver_98081b0->resolve('139.162.61.246')
#4 /var/www/publisher/src/SWP/Bundle/MultiTenancyBundle/EventListener/TenantableListener.php(64): SWP\Bundle\CoreBundle\Context\CachedTenantCon" while reading response header from upstream, client: 14.143.15.70, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "139.162.61.246"

How to fix this issue?

**Comment by takeit** [comment]
Hi @jvkiran,

looks like the tenant with domain set to `139.162.61.246` existing in the database twice. Try to remove one row with the same domain.

Did you create it manually in the database? What were the steps that caused that issue?

**Comment by jvkiran** [comment]
Hi @takeit,
Error got fixed, After deleted duplicate tenant from DB.
I had tenant create command twice, so two tenant are created in DB.
Thanks for point exact solution.
