### ISSUE TITLE
Tenant for host "127.0.0.1" could not be found! 

### ISSUE THREAD

**Issue by jvkiran** [superdesk/web-publisher#535]
In Database table swp_tenant has value 127.0.0.1 in domain field.
still getting following error.

2018/06/07 09:10:39 [error] 1105#1105: *33 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught SWP\Component\MultiTenancy\Exception\TenantNotFoundException: Tenant for host "127.0.0.1" could not be found! in /var/www/publisher/src/SWP/Component/MultiTenancy/Resolver/TenantResolver.php:58
Stack trace:
#0 /var/www/publisher/app/cache/prod/ContainerEfjtltv/TenantResolver_98081b0.php(13): SWP\Component\MultiTenancy\Resolver\TenantResolver->resolve('example.com')
#1 /var/www/publisher/src/SWP/Bundle/CoreBundle/Context/CachedTenantContext.php(74): TenantResolver_98081b0->resolve('127.0.0.1')
#2 /var/www/publisher/src/SWP/Bundle/MultiTenancyBundle/EventListener/TenantableListener.php(64): SWP\Bundle\CoreBundle\Context\CachedTenantContext->getTenant()
#3 /var/www/publisher/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): SWP\Bundle\MultiTenancyBundle\EventListener\TenantableListener->enable(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAware" while reading response header from upstream, client: 14.143.15.70, server: 127.0.0.1, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"

**Comment by ahilles107** [comment]
Hey, we will check it. Imo you can try with `localhost` - this should work. But with IP address as a tenant it can fail.

**Comment by jvkiran** [comment]
it's works, Thanks you.

**Comment by jvkiran** [comment]
it's works, Thanks you.
