### ISSUE TITLE
Superdesk published items are not sync in wordpress site

### ISSUE THREAD

**Issue by jvkiran** [superdesk/web-publisher#538]
Hi,
I've setup web-publisher in example.com and wordpress site in wp.example.com.
After i activate superdesk-wordpress-plugin in wordpress site, 

**i Filled following details:**
SD content api url : superdesk.com/contentapi
client id: no idea, which value should i put here.
username: superdesk login username
password: superdesk login password

is that correct, or anything missing from superdesk or publisher component.
can someone pls help on this.

Thanks in advance.

**Comment by ahilles107** [comment]
@superdesk/superdesk-core ? This wordpress plugin is not maintained by Publisher team. We developed in last weeks some other solution for sync with wordpress (https://superdesk-publisher.readthedocs.io/en/latest/cookbooks/implementators/wordpress_output_channel.html). It does not have yet ui. But with api you can create tenant with output channel set to wordpress. Better docs will be created soon.
