### ISSUE TITLE
[RFC] Tenant aware themes

### ISSUE THREAD

**Issue by takeit** [superdesk/web-publisher#55]
**Introduction**
- Load themes for current tenant. The repository should not collect all available themes belonging to other tenants - this will be the performance improvement when loading themes for the first time.

**Proposal**

The Sylius Theme Bundle has been refactored a lot, thus the below proposal is not valid anymore. See [this RFC issue](https://github.com/Sylius/Sylius/issues/4280) for more details:

- ~~disable ThemeRepository compiler pass in ThemeBundle~~
- ~~When creating a new tenant (e.g. `tenant1`) it should also  create a new directory in `app/themes/tenant1` where themes will be kept for given tenant. (the dir should be removed when tenant will be deleted)~~
- ~~In `ActiveThemeListener` Event listener (which will be created on our side) there should be `TenantContext` injected to get current tenant. Based on tenant's subdomain we will search in `/app/themes/tenant1` dir for  its available themes (worth to take a look into `FilesystemConfigurationProvider` from ThemeBundle)~~

~~Here we can extend Sylius `RecursiveFileLocator` where we will inject `TenantContext` and prefix the `$paths` array (https://github.com/Sylius/SyliusThemeBundle/blob/master/Locator/RecursiveFileLocator.php#L40) with current tenant, so it will read themes from `app/themes/tenant1` in that case.~~

- ~~found themes should be then added to Sylius `ThemeRepository`~~
- ~~then in the `ThemeRepository` it should find the theme used by the current tenant and set it to active~~

**Drawbacks**

- ~~we should make it configurable to disable/enable ThemeRepositoryPass in Sylius ThemeBundle~~
- ~~remove 'final' from some classes to allow override in Sylius ThemeBundle~~
- ~~make sure the cache should not be cleared when uploading changing themes - ThemeBundle should take care about this? - research it.~~
- ~~dump assets for all themes, not only for current tenant~~

**References**
- [Sylius ThemeBundle](https://github.com/Sylius/SyliusThemeBundle)

**Comment by ahilles107** [comment]
:+1:
