### ISSUE TITLE
[RFC] Device specific templates 

### ISSUE THREAD

**Issue by ahilles107** [superdesk/web-publisher#56]
This RFC is about porting part of liip/LiipThemeBundle feature: https://github.com/liip/LiipThemeBundle#device-specific-themestemplates 

You can provide specific templates for different devices (like: desktop, tablet, phone, plain). Set option autodetect_device to true for setting current_device parameter based on the user agent:
````
# app/config/config.yml
sylius_theme:
    autodetect_device: true
````
Then in resource locator will use %%current_device%% parameter (with your device type as value)

New app resource path:
````
%%current_theme%%/%%current_device%%/%%template%%
````
New bundle resource path:
````
%%current_theme%%/%%current_device%%/%%current_bundle%%/%%template%%
````
Optionally autodetect_theme can also be set to a DIC service id that implements the ```DeviceDetectionInterface``` interface.

**Comment by takeit** [comment]
:+1:
