### ISSUE TITLE
Cannot access uploaded files

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [superdesk/web-publisher#568]
Hi,

I've created articles in Superdesk with attachments (e.g. pdfs) and pushed it to publisher, but when I try to access any of these files I reach a 404.

I want to embed a PDF in the article, but when I try this it just gives a frame with a 404 error in it. Is there also an easier way to embed the PDF? If I add the following:

    <iframe id="iframepdf" src="myattachment.pdf "></iframe>

The article fails the validation test and I can't post it, the way I've been trying to get it to work is by uploading the file (and checking it's added to swp_file), then modifying the swp_article to add the following to the body:

    <iframe id="iframepdf" src="/media/5b3b4c5ef31b6605a4f73c31.pdf"></iframe>

**Comment by ahilles107** [comment]
Hey, 

we don't have yet support for other files than images in publisher (PR's are welcome). 

Uploading file manually will not create required info in database.

**Comment by ahilles107** [comment]
Pdf's - I would recommend to store them right now in some external system and link to it's storage in articles. 

> I've ported a wordpress site to publisher. All I did to get that working was rename the images to hashes of themselves and then add the record to swp_image. Is that not enough? For feature images, thumbnails, etc. I did also add records to swp_article_media, swp_image_rendition, etc.

For migrations I would recommend to create ninja files from Newscoop articles and handle media upload with assets push endpoint (this same way as super desk publishing queue) - if You don't use superdesk. If You use then best would be to import them to sd directly and push to publisher. We are doing this right now like that.

> I also came across another bug (?) while doing that. Images added to the database have to be in the media folder, if I add them to e.g. '/media/2012/feb/a.jpg', and do or don't use that path as the asset_id then it still doesn't work? Should it not work?

For now media files are stored in flat structure, this is how media controller is loading them. We are open for improvements there ;)
