### ISSUE TITLE
"Tenant for host 123abc not found" on install with docker. 

### ISSUE THREAD

**Issue by Denvervintage** [superdesk/web-publisher#617]
using  code "sudo docker-compose run php app/console swp:theme:install 123abc src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/ -f -p" 
Returns the error 
"Tenant for host "123abc" could not be found"

following install instructions here: https://github.com/superdesk/web-publisher/blob/master/docker/README.md

![error](https://user-images.githubusercontent.com/42973758/45041796-6b491e80-b026-11e8-9452-63115ace65df.JPG)

**Comment by takeit** [comment]
hi @Denvervintage, thanks for reporting that issue.

I checked it and I can not reproduce it. Did you execute all commands step by step?

Looks like `doctrine:fixtures:load` command was not executed. You have to load fixtures as described [here](https://github.com/superdesk/web-publisher/blob/master/docker/README.md#load-fixtures).

**Comment by Denvervintage** [comment]
Ok, thinking maybe i skipped a step, I went back and wiped the server and started from scratch 3 times. 
Fresh server
update ubuntu
(Composer and docker do not work from clone)
install docker
install composer
update / upgrade 
Test.  All is working. 

Run 
docker-compose build
Run 
docker-compose up -d
Run

**Comment by Denvervintage** [comment]
Ok, thinking maybe i skipped a step, I went back and wiped the server and started from scratch 3 times.
Fresh server
update ubuntu
(Composer and docker do not work from clone)
install docker
install composer
update / upgrade
Test. All is working.

Run
docker-compose build
Run
docker-compose up -d
Run
docker-compose run php composer install
Configure paramaters yml  (Exactly as shown on the readme.md)
Run 
docker-compose run php app/console doctrine:database:create
Run

**Comment by Denvervintage** [comment]
Ok, thinking maybe i skipped a step, I went back and wiped the server and started from scratch 3 times.
Fresh server fresh ubuntu install
update and upgrade ubuntu
Clone repository. 

(Composer and docker do not work from cloned repository)
Inside web-publisher folder:
install docker
install composer
apt-get update / upgrade

Test. All is working.

Run
docker-compose build

Run
docker-compose up -d

Run
docker-compose run php composer install
Configure paramaters yml (Exactly as shown on the readme.md)

Run
docker-compose run php app/console doctrine:database:create

Run
docker-compose run php app/console doctrine:migrations:migrate

Run 
docker-compose run php app/console doctrine:fixtures:load

Run
docker-compose run php app/console swp:theme:install 123abc src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/ -f -p

Exact same error 
"Tenant for host "123abd" could not be found!"
![capture](https://user-images.githubusercontent.com/42973758/45639783-24b7e300-ba6e-11e8-8c39-5b1a01169083.JPG)
[putty.txt](https://github.com/superdesk/web-publisher/files/2389635/putty.txt)
