### ISSUE TITLE
Js Error: Cannot read property 'getElementsByTagName' of null

### ISSUE THREAD

**Issue by finchen** [superdesk/web-publisher#630]
Hi,

I just followed the install instruction from 
https://superdesk-publisher.readthedocs.io/en/latest/manual/getting_started/superdesk-superdesk-publisher-setup.html

I am on _master_ branch
 master 1030783 [origin/master] AWS file storage (#626)

I get the JS error in 
` blueimp.Gallery(document.getElementById("links").getElementsByTagName("a"), {
        container: "#blueimp-gallery-carousel",
        carousel: !0
    })`

Uncaught TypeError: Cannot read property 'getElementsByTagName' of null

There is no elements `links` on the page
Is it a javascript file to update or a problem with the theme?

Thanks

**Comment by ahilles107** [comment]
Hey, yep it's know bug of demo theme. This script is not used there anymore and should be removed (pr's are welcome). It shouldn't change theme behaviour. If You don't see assets at all then run assets theme install command.

**Comment by finchen** [comment]
ok. Not ready for PM yet but I might contribute one day! First I am trying to set up everything and evaluate if we are going to use it.

I thought that error was blocking the javascript and prevent the sign in to admin panel. (sign in seems to show a pop up but it does not)

**Comment by ahilles107** [comment]
Publisher doesn't have admin panel ;) It's located in Superdesk (with Publisher plugin enabled). Demo theme is used for development. So i'm not even sure if there are some user features implemented  in this theme. If You want to know more about project and architecture - read our docs https://superdesk-publisher.readthedocs.io/en/latest/
