### ISSUE TITLE
Installation Issue - fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by mikeavena** [superdesk/web-publisher#634]
Hello,

I'm trying to install Superdesk Publisher on a clean install of Ubuntu 16.04. I was able to complete all the installation steps from https://superdesk-publisher.readthedocs.io/en/latest/manual/getting_started/superdesk-superdesk-publisher-setup.html up until step 4 (Create the database and update the scheme). With the first database command I get the error 'SQLSTATE[08006] [7] fe_sendauth: no password supplied'. Here is my parameters.yml file:

```
parameters:
    locale: en
    env(DATABASE_HOST): 127.0.0.1
    env(DATABASE_PORT): null
    env(DATABASE_NAME): publisher
    env(DATABASE_USER): postgres
    env(DATABASE_PASSWORD): postgres
    env(DATABASE_SERVER_VERSION): 9
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    env(SYMFONY_SECRET): SuperSecretTokenPleaseChangeIt
    swp_updater.version.class: SWP\Bundle\CoreBundle\Version\Version
    env(SWP_DOMAIN): 45.33.84.234
    cache_servers:
        - 45.33.84.234
    doctrine_cache_driver: array
    sentry.dsn: false
    session_memcached_host: localhost
    session_memcached_port: 11211
    session_memcached_prefix: sess
    session_memcached_expire: 3600
    test_env: doctrine
    allow_origin_cors: 'http://localhost'
    superdesk_servers:
        - 'https://superdesk.dev'
    env(ELASTICA_HOST): localhost
    env(ELASTICA_PORT): 9200
    env(ELASTICA_INDEX_NAME): swp_index
    env(RABBIT_MQ_HOST): 127.0.0.1
    env(RABBIT_MQ_PORT): 5672
    env(RABBIT_MQ_USER): guest
    env(RABBIT_MQ_PASSWORD): guest
    env(WEBSOCKET_PORT): 8080
    env(WEBSOCKET_HOST): 127.0.0.1
    env(PAYWALL_SERVER_URL): null
    env(PAYWALL_SERVER_USERNAME): null
    env(PAYWALL_SERVER_PASSWORD): null
    env(SUBSCRIPTIONS_CACHE_LIFETIME): 86400
    fixtures_type: '%env(FIXTURES_TYPE)%'
    env(FIXTURES_TYPE): dev
    JWT_PASS_PHRASE: null
    FS_MAIN_ADAPTER: local_adapter
    env(FS_AWS_S3_VERSION): null
    env(FS_AWS_S3_REGION): null
    env(FS_AWS_S3_KEY): null
    env(FS_AWS_S3_SECRET): null
    env(FS_AWS_S3_PREFIX): null
    env(FS_AWS_S3_BUCKET): null
```

Any idea what I might be doing wrong?

**Comment by ahilles107** [comment]
Yep, it's `pg_hba.conf` configuration connected. Publisher can't connect to this database with provided credentials. This can help You: https://stackoverflow.com/questions/3278379/how-to-configure-postgresql-to-accept-all-incoming-connections

**Comment by mikeavena** [comment]
For anyone facing the same issue, I figured it out. By coming back to it and mistakenly entering the second SQL command in the instructions, I got the error `SQLSTATE[08006] : role "root" does not exist`. I solved this with an answer from https://github.com/taigaio/taiga-back/issues/387 and added a user named "root" to postgres. Next, I upgraded the root user to a superuser. After that, everything worked just fine. I don't know why it was looking for a user named root instead of the one specified in parameters.yml.

Now, I have no idea if this was actually a secure way of installing this. I'm only testing right now, so I'm not super concerned, but @ahilles107 would you be able to give feedback about this?

**Comment by ahilles107** [comment]
I'm not sure how it should be done on postgres configuration. I never had to create root user - i always create new user and database for publisher instance.
