### ISSUE TITLE
"Composer Install" with Composer version 1.7.3 2018-11-01 10:05:06 fails

### ISSUE THREAD

**Issue by ioncebotari** [superdesk/web-publisher#651]
When running "composer install" with today's Composer I get the following error:
Reading ./composer.lock
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Resolving dependencies through SAT

Dependency resolution completed in 0.001 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/symfony v3.4.14 -> satisfiable by symfony/symfony[v3.4.14].
    - don't install symfony/dotenv v4.1.4|don't install symfony/symfony v3.4.14
    - Installation request for symfony/dotenv v4.1.4 -> satisfiable by symfony/dotenv[v4.1.4].

**Comment by takeit** [comment]
Hi @ioncebotari, please try the [1.4 branch](https://github.com/superdesk/web-publisher/tree/1.4) for now. We will fix that issue in master in the upcoming days.
