### ISSUE TITLE
Dependency problems: Log4PHP git repository returns a 404 

### ISSUE THREAD

**Issue by ioncebotari** [superdesk/web-publisher#672]
I can't install webpublisher because a dependency isn't accessible anymore. The Log4PHP repository at https://git-wip-us.apache.org/repos/asf/logging-log4php.git returns 404 code, so Composer is unable to install it

**Comment by takeit** [comment]
Hi @ioncebotari 

you can try to install it from my branch were I hotifxed that issue: https://github.com/takeit/web-publisher/tree/users_migration

we will take a look at it. Thanks

**Comment by takeit** [comment]
it has been fixed and merged to 1.4 branch. Please use 1.4 branch instead of master.
