### ISSUE TITLE
sha1 computation mismatched

### ISSUE THREAD

**Issue by shivharis** [superdesk/web-publisher#678]
asset url sha1 computation uses data of file to compute sha1, should use all of the content sent.

**Comment by ahilles107** [comment]
@shivharis - data are sent from Superdesk to Publisher in form of `multipart/form-data`. And it's impossible to read the original request from that format in userland (in php). We are exploring now possible options. To make it work now you can comment line 58 of https://github.com/superdesk/web-publisher/blob/d3bf7fede8f2a349020495ad0b0759b36c07888d/src/SWP/Bundle/CoreBundle/EventListener/SecuredContentPushListener.php#L58. This way content will be still secured, and assets will be allowed (stored) without check.
