### ISSUE TITLE
Unable to add Publisher to superdesk

### ISSUE THREAD

**Issue by sushritcode** [superdesk/web-publisher#703]
Have installed Superdesk and SuperDesk-Publisher on 2 different servers(ubuntu 16.04) using the steps in 

https://superdesk-publisher.readthedocs.io/en/latest/manual/getting_started/superdesk-superdesk-publisher-setup.html#how-to-configure-superdesk-publisher-with-superdesk

After updating the config file (config.js and config.e34553.js) on Superdesk , Superdesk fails to load in the browser , the network tab of the Firebug shows "Module 'superdesk-publisher' is not available! "

The URLs of the set up are as follows : 

Superdesk : http://ec2-13-233-253-231.ap-south-1.compute.amazonaws.com/
Superdesk-Publisher : http://ec2-13-233-89-104.ap-south-1.compute.amazonaws.com/

** on reverting back the config files to original Superdesk works fine.
Please help !!! 
Thanks in Advance

**Comment by takeit** [comment]
@tomaszrondio any idea?

**Comment by tomaszrondio** [comment]
Double check config variables. Maybe there is some typo in Publisher domain. Other than that it should work. I never experienced that kind of error.
