### ISSUE TITLE
[RFC] Consider dropping PHP 5.6 - support PHP >= 7

### ISSUE THREAD

**Issue by takeit** [superdesk/web-publisher#74]
The idea here is to drop support for PHP 5 at all and support only 7. Most of the libraries already support PHP 7, thus it's an adventage for us. We are developing a new project so we should consider using the latest technologies - PHP 7 in this case.

**Pros:**
- PHP 7 is out, we should go for it!
- significant improvement in performance
- lots of new awesome features: http://php.net/manual/en/migration70.new-features.php
- active support until 3 Dec 2017
- Security Support Until 3 Dec 2018

**Cons:**
- we might stuck with some libraries that don't support PHP 7
- some extensions like `imagick`, `gearman` are not supporting PHP 7 fully yet (see [Extensions catalogue](https://github.com/gophp7/gophp7-ext/wiki/extensions-catalog)

**What needs to be done to fully switch to PHP 7:**
- use PHP ^7.0 in Web Publisher `composer.json` file
- use PHP ^7.0 in all of our bundles (`composer.json`)
- update `travis.yml` config
- re-check Docker configuration
- ~~migrate code from PHP 5.6 to 7 (see http://php.net/manual/en/migration70.php)~~ - tests are passing on PHP 7 so it's not needed.
- re-check documentation

**Reference:**
- Extensions catalogue: https://github.com/gophp7/gophp7-ext/wiki/extensions-catalog
- PHP 7 features: http://php.net/manual/en/migration70.new-features.php

Please, add your feedback here.

**Comment by ahilles107** [comment]
Ass all our tests passes php7 then no work is required for code migration. We could just start using php7 features and all should work this same as before. About not supported extension - we never used any of them, for images we use supported GD.  

I'm huge :+1: for this change.

**Comment by djbrd-sourcefabric** [comment]
This is a no brainer

**Comment by hlmnrmr** [comment]
Let's do it! 7 has been out for a while now and will continue getting more and more acceptance. As @takeit mentioned, we are in early development stages of a new project, it is the time to do it and by the time we will approach a first release, 7 will be even better.

**Comment by ahilles107** [comment]
Implemented in #153
