### ISSUE TITLE
Superdesk Publisher installation fails

### ISSUE THREAD

**Issue by dsmackie** [superdesk/web-publisher#743]
When following the instructions at https://www.superdesk.org/news/installing-superdesk-publisher the installation fails.

Step 2 of `Completing the Superdesk Publisher installation`;

`HTTPDUSER=$(ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1) && sudo chown -R "$HTTPDUSER":"$HTTPDUSER" publisher/ && cd publisher && sudo -u www-data SYMFONY_ENV=prod composer install --no-dev --optimize-autoloader`

Error:

```
  Problem 1
    - Installation request for react/zmq dev-master -> satisfiable by react/zmq[dev-master].
    - react/zmq dev-master requires ext-zmq * -> the requested PHP extension zmq is missing from your system.
```

**Comment by dsmackie** [comment]
Step 3 of the Setting up the server/VPS requires the following addition;

`php7.2-zmq` to Line 5

**Comment by dsmackie** [comment]
As a side note, I can not get any of the installation instructions to work. Neither a pure server or Docker instance.

**Comment by takeit** [comment]
Right, this guide is a bit outdated and was compatible with Publisher v1.3. We will have to update this guide.

Did you install php7.2-zmq? What errors do you have now?

**Comment by dsmackie** [comment]
> Did you install php7.2-zmq? What errors do you have now?

Adding the `php7.2-zmq` requirement has allowed me to make progress. I will advise if I run into any other issues.

Regarding the docker issues, I will raise a new ticket when I try again shortly.

**Comment by takeit** [comment]
Great, thanks I will assist you with any further issues. Thanks on our progress we will update this installation guide.

**Comment by dsmackie** [comment]
The prerequisites lists `memcached` however the guide never asks to install it. It is recommended to add `sudo apt install memcached` to the installation guide.

Possibly related to the memcached version, `Step 7. Install theme` fails with the following error;

`22:17:23 CRITICAL  [app] 405 error response "Method Not Allowed" from caching proxy ["exception" => FOS\HttpCache\Exception\ProxyResponseException { …}]
`
