### ISSUE TITLE
Unauthorized (user not found in Superdesk)

### ISSUE THREAD

**Issue by dsmackie** [superdesk/web-publisher#744]
I have two servers; 1 x Superdesk, 1 x Superdesk Publisher. They are both configured as per the installation guides.

When logging in to the Superdesk administration page, the site does not display the Superdesk Publisher site that has been configured in config.js.

The API call to the publisher is failing as shown below;

![image](https://user-images.githubusercontent.com/48046804/53564317-a9289900-3baa-11e9-8bd2-fb4f5a4bc9b9.png)

The `prod.log` file shows the following;

`[2019-02-28 22:32:53] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api/sessions/5c77c6c65ab77e30ab0c38c1"" at /var/www/publisher/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/sessions/5c77c6c65ab77e30ab0c38c1\" at /var/www/publisher/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /api/sessions/5c77c6c65ab77e30ab0c38c1 HTTP/1.1\r\nAuthorization:  Basic MDY2ODMyY2EtOWEwNi00ZWE3LTlmZjgtMDgxOGYyMzZlOWQ2Og==\r\nContent-Length: \r\nContent-Type:   \r\nHost:           192.168.100.211\r\nPhp-Auth-Pw:    \r\nPhp-Auth-User:  066832ca-9a06-4ea7-9ff8-0818f236e9d6\r\nUser-Agent:     GuzzleHttp/6.3.3 curl/7.47.0 PHP/7.2.15-1+ubuntu16.04.1+deb.sury.org+1\r\nX-Php-Ob-Level: 1\r\n\r\n at /var/www/publisher/vendor/symfony-cmf/routing/src/ChainRouter.php:210)"} []`

**Comment by dsmackie** [comment]
Chrome console shows the following;

`Possibly unhandled rejection: {"data":{"status":401,"message":"Unauthorized (user not found in Superdesk)"},"status":401,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"http://192.168.100.211/api/v1/auth/superdesk/","data":{"auth_superdesk":{"session_id":"5c77c6c65ab77e30ab0c38c1","token":"Basic MDY2ODMyY2EtOWEwNi00ZWE3LTlmZjgtMDgxOGYyMzZlOWQ2Og=="}},"add_format":"json","headers":{"Authorization":"Basic undefined","Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Unauthorized","xhrStatus":"complete"}`

**Comment by takeit** [comment]
what shows to you when in chrome console you run `window.superdeskConfig` in your Superdesk admin panel?

**Comment by takeit** [comment]
It looks like the user has not been created, try to log out and log in in Superdesk and try again, otherwise clear the cache in your Publisher installation: `rm -rf app/cache/*`

**Comment by dsmackie** [comment]
The correct details as far as the installation guide says.

![image](https://user-images.githubusercontent.com/48046804/53564752-d164c780-3bab-11e9-89f3-d04769dadb72.png)

**Comment by dsmackie** [comment]
Clearing the cache and logging out and in has not fixed the problem.

The same error as above is appearing.

**Comment by dsmackie** [comment]
Should the following have `api/v1/`?

https://github.com/superdesk/web-publisher/blob/0f54258d0d99a7051002249f8e761ed6d1859031/src/SWP/Bundle/CoreBundle/Controller/AuthController.php#L106

**Comment by ahilles107** [comment]
In publisher config you need to set superdesk instance url under `superdesk_servers` config param (parameters.yml). It works like that: There is token from superdesk ui to server with user key, and at first request publisher ask back that superdesk server if that user really exists. Both - superdesk and publisher need to know about each other.
