### ISSUE TITLE
 This package requires php ^7.3 but your HHVM version does not satisfy that requirement.

### ISSUE THREAD

**Issue by dkoryto** [superdesk/web-publisher#862]
sudo -u www-data SYMFONY_ENV=prod composer install --no-dev --optimize-autoloader
Cannot create cache directory /home/xxx/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/xxx/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - **This package requires php ^7.3 but your HHVM version does not satisfy that requirement.**

The instruction says nothing about the installation php7.3
https://www.superdesk.org/news/installing-superdesk-publisher only php7.2

**Comment by ahilles107** [comment]
Hey @dkoryto , 

Blog instruction can be not in sync with latest version requirements. 
You can find current requirements in our README file or best in composer.json (https://github.com/superdesk/web-publisher/blob/master/composer.json#L53) 

Publisher require php 7.3 in master (will soon be released as 2.0) branch (7.1 in latest stable 1.5 branch).
