### ISSUE TITLE
Cant connect Superdesk to Superdesk publisher

### ISSUE THREAD

**Issue by sarveshwaranj** [superdesk/web-publisher#976]
My superdesk is running in http://192.168.1.25 and my superdesk web-publisher is running in http://192.168.1.25:8000/
![image](https://user-images.githubusercontent.com/52163159/66827899-5b13aa80-ef6d-11e9-9b53-0524e7536256.png)
![image](https://user-images.githubusercontent.com/52163159/66827959-83030e00-ef6d-11e9-959a-ff12eee6e8c3.png)
But I cannot see Publisher in the superdesk and when I give publish I got the below error

**Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.1.25:8000/api/v2/auth/superdesk/. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘null’).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.1.25:8000/api/v2/auth/superdesk/. (Reason: CORS request did not succeed).**

And my config.js file is this

window.superdeskConfig = {
    apps: ['superdesk-publisher'],
    publisher: {
        protocol: "http",
        tenant: '', // subdomain
        domain: '192.168.1.25:8000', // IP address or domain name of your server where Superdesk Publisher is installed
        base: 'api/v1'
    },
};

And my **organization code** : x52wws
**tenant code** : y3fbp9

Wheather I have to use the tenant in config.js file 

Please solve the above problems

**Comment by ahilles107** [comment]
What fo You have in publisher logs? How looks your `SUPERDESK_SERVERS` env value?

**Comment by ahilles107** [comment]
Plus check if `CORS_ALLOW_ORIGIN` is properly configured. It Should allow connection from `192.168.1.25`

**Comment by sarveshwaranj** [comment]
**My env file is** 
# In all environments, the following files are loaded if they exist,
# the later taking precedence over the former:
#
#  * .env                contains default values for the environment variables needed by the app
#  * .env.local          uncommitted file with local overrides
#  * .env.$APP_ENV       committed environment-specific defaults
#  * .env.$APP_ENV.local uncommitted environment-specific overrides
#
# Real environment variables win over .env files.
#
# DO NOT DEFINE PRODUCTION SECRETS IN THIS FILE NOR IN ANY OTHER COMMITTED FILES.
#
# Run "composer dump-env prod" to compile .env files for production use (requires symfony/flex >=1.2).
# https://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration
 ###> symfony/framework-bundle ###
APP_ENV=dev
APP_DEBUG=1
APP_SECRET=CHANGEME
APP_LOCALE=en
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS=localhost,example.com
###< symfony/framework-bundle ###

 ###> doctrine/doctrine-bundle ###
# Format described at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# For a sqlite database, use: "sqlite://%kernel.project_dir%/var/data.db"
# Set "serverVersion" to your server version to avoid edge-case exceptions and extra database calls
DATABASE_URL=pgsql://postgres:postgres@192.168.1.25:5432/publisher_%kernel.environment%?charset=utf8&serverVersion=9
DOCTRINE_CACHE_DRIVER=memcached
###< doctrine/doctrine-bundle ###

###> symfony/swiftmailer-bundle ###
# For Gmail as a transport, use: "gmail://username:password@localhost"
# For a generic SMTP server, use: "smtp://localhost:25?encryption=&auth_mode="
# Delivery is disabled by default via "null://localhost"
MAILER_URL=smtp://localhost
###< symfony/swiftmailer-bundle ###

SWP_DOMAIN=localhost

FS_MAIN_ADAPTER=local_adapter
FS_AWS_S3_VERSION=latest
FS_AWS_S3_REGION=
FS_AWS_S3_KEY=
FS_AWS_S3_SECRET=
FS_AWS_S3_PREFIX=
FS_AWS_S3_BUCKET=

CACHE_SERVERS='["localhost"]'
SUPERDESK_SERVERS='["localhost:3000"]'

###> sentry/sentry-symfony ###
SENTRY_DSN=false
###< sentry/sentry-symfony ###

SESSION_MEMCACHED_HOST=localhost
SESSION_MEMCACHED_PORT=11211
SESSION_MEMCACHED_PREFIX=sess
SESSION_MEMCACHED_EXPIRE=3600

###> nelmio/cors-bundle ###
CORS_ALLOW_ORIGIN='http://localhost'
###< nelmio/cors-bundle ###

RABBIT_MQ_HOST=127.0.0.1
RABBIT_MQ_PORT=5672
RABBIT_MQ_USER=guest
RABBIT_MQ_PASSWORD=guest
RABBIT_MQ_VHOST=/

WEBSOCKET_PORT=8080
WEBSOCKET_HOST=127.0.0.1
WEBSOCKET_QUEUE_NAME=swp_websocket
WEBSOCKET_EXCHANGE_NAME=swp_websocket_exchange

PAYWALL_SERVER_URL=localhost
PAYWALL_SERVER_USERNAME=
PAYWALL_SERVER_PASSWORD=

SUBSCRIPTIONS_CACHE_LIFETIME=86400

FIXTURES_TYPE=dev

ELASTICA_HOST=localhost
ELASTICA_PORT=9200
ELASTICA_INDEX_NAME='swp_index'

TEST_ENV=doctrine

###> php-amqplib/rabbitmq-bundle ###
RABBITMQ_URL=amqp://guest:guest@localhost:5672
###< php-amqplib/rabbitmq-bundle ###

###> lexik/jwt-authentication-bundle ###
JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
JWT_PASSPHRASE=5452ca2757732594ee847d58c0cd7508
###< lexik/jwt-authentication-bundle ###

ANALYTICS_HOST=
ELASTICA_ARTICLE_EXTRA_FIELDS='[]'

SLUG_REGEX=
WEBP_CONVERSION_ENABLED=true
REDIRECT_NOT_FOUND_ARTICLES_TO_ROUTE=false
SUPERDESK_THUMBNAIL_RENDITION_NAME=original
SUPERDESK_VIEW_IMAGE_RENDITION_NAME=original

LOG_DOMAIN=
LOG_PORT=

EXTERNAL_OAUTH_CLIENT_ID=
EXTERNAL_OAUTH_CLIENT_SECRET=
EXTERNAL_OAUTH_BASE_URL=

**Comment by sarveshwaranj** [comment]
Where to find the CORS_ALLOW_ORIGIN ?? 
In publisher or superdesk
And I got this when I publish the package
![image](https://user-images.githubusercontent.com/52163159/66888028-acb64680-effa-11e9-81e9-6511b65e3c4c.png)

**Comment by sarveshwaranj** [comment]
I have changed  CORS_ALLOW_ORIGIN and  SUPERDESK_SERVERS to my ip 192.168.1.25 But still the problem occurs

**Comment by ahilles107** [comment]
Hey, first read how you should work with .env files: https://symfony.com/doc/current/configuration.html#managing-multiple-env-files Your custom values should be placed in `.env.local`. 

`Web publisher is loading for the first time, but after reload it is not working` doesn't tell me much ;( Please show me your response code from publisher and errors found in log files.

**Comment by ahilles107** [comment]
@sarveshwaranj  ping ;)
