### ISSUE TITLE
CAN'T SEE SUPERDESK PUBLISHER HOME PAGE

### ISSUE THREAD

**Issue by eugeneonos** [superdesk/web-publisher#998]
I have followed https://github.com/superdesk/web-publisher/blob/2.0/INSTALL.md to install the various components of Superdesk publisher and running supervisorctl has the following output

publisher_analytics              RUNNING   pid 9722, uptime 0:15:32
publisher_content_push           RUNNING   pid 9726, uptime 0:15:32
publisher_image_conversion       RUNNING   pid 9723, uptime 0:15:32
publisher_webhooks               RUNNING   pid 9724, uptime 0:15:32
publisher_websocket              RUNNING   pid 9725, uptime 0:15:32
supervisor>

And my apache2 is equally running as below

 ps -ef|grep apache2
root      9192     1  0 Nov14 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  9195  9192  0 Nov14 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  9196  9192  0 Nov14 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  9197  9192  0 Nov14 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  9198  9192  0 Nov14 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  9199  9192  0 Nov14 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  9205  9192  0 Nov14 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  9837  9192  0 00:02 ?        00:00:00 /usr/sbin/apache2 -k start
root     10611  6777  0 00:16 pts/4    00:00:00 grep --color=auto apache2

However, when I follow the guide to attempt http://myhost/, all I get is the apache2 index.html default page. I do not see the Superdesk Publisher page.
Please do I need to do something to the apache 'sites-available' or any other?

Many thanks for your help.

**Comment by ahilles107** [comment]
apache vhost config for projects based on Symfony (like Publisher is) can be found here: https://symfony.com/doc/current/setup/web_server_configuration.html
